-- AlterTable
ALTER TABLE "tb_cep" ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "cidade" DROP NOT NULL,
ALTER COLUMN "cod_ibge" DROP NOT NULL,
ALTER COLUMN "ddd" DROP NOT NULL,
ALTER COLUMN "state" DROP NOT NULL;
